---
title: "hw03-Meiying-Huang-rmd"
author: "Meiying Huang"
date: "10/12/2017"
output: github_document
---
```{r}
library(readr)
library(dplyr)
library(ggplot2)
dat1 <- read.csv('./nba2017-roster.csv', stringsAsFactors = FALSE)
dat2<- read.csv('./nba2017-stats.csv', stringsAsFactors = FALSE)
```

```{r}
##adding new variables
dat2$missed_fg=dat2$field_goals_atts-dat2$field_goals_made
dat2$missed_ft=dat2$points1_atts-dat2$points1_made
dat2$points=3*dat2$points3_made+2*dat2$points2_made+dat2$points1_made
dat2$rebounds=dat2$off_rebounds+dat2$def_rebounds
dat2$efficiency=((dat2$points+dat2$rebounds+dat2$assists+dat2$steals+dat2$blocks-dat2$missed_fg-dat2$missed_ft-dat2$turnover)/(dat2$games_played))

dat3<-cbind(player=dat2$player,dat2$missed_fg,dat2$missed_ft,dat2$points,dat2$rebounds,dat2$efficiency)

sink(file= '/Users/liminhuang/hw03/output/efficiency-summary.txt')
## summary(efficiency)
sink()
```

```{r}
##merging tables
dat4<-merge(dat1,dat2)
```

```{r}
##ceating nba2017-teams.csv
# dat4$team <- as.factor(dat$team)
teams <- dat4 %>% 
  group_by(team) %>%
  summarise(experience = sum(experience),
                  salary=round(sum(salary/1000000), digits=2),
                  points3=sum(points3_made),
                  points2=sum(points2_made),
                  free_throws=sum(points1_made),
                  points=sum(3*points3_made+2*points2_made+points1_made),
                  off_rebounds=sum(off_rebounds),
                  def_rebounds=sum(def_rebounds),
                  assists=sum(assists),
                  steals=sum(steals),
                  blocks=sum(blocks),
                  turnovers=sum(turnovers),
                  fouls=sum(fouls),
                  efficiency=sum(efficiency))
summary(teams)
class(dat4$team)
unique(dat4$team)
```

```{r}
##sink team summary
sink(file= '/Users/liminhuang/hw03/data/teams-summary.txt')
summary(teams)
sink()
```

```{r}
##export teams to a csv named nba2017-teams.csv
write.csv(teams,file="/Users/liminhuang/hw03/data/nba2017-teams.csv",row.names=FALSE)
```

```{r}
##graphics named: teams_stat_plot.pdf
stars(teams[,-1],labels = teams$team)
pdf(file="/Users/liminhuang/hw03/images/teams_stat_plot.pdf", width=6.5, height = 5)
dev.off()
```

```{r}
##a scatterplot of experience,salary,teams, save the plot in the file "experience_salary.pdf" inside the images folder
ggplot(data=teams, aes(x=experience,y=salary))+
  geom_label(aes(label= team), alpha=0.8,hjust=1,vjust=1)+
  ggtitle("Experience and Salary")
pdf(file = "/Users/liminhuang/hw03/images/experience-salary.pdf")
dev.off()
```


```{r}
##1ranking: rank the teams according to salary,in decreasing order.ggplot to create a barchat(horizontally oriented), add a vertical red line - the average team salary
teams<-arrange(teams,desc(salary))
ggplot(teams,aes(x=reorder(team,salary),y=salary))+
  geom_bar(stat='identity',color="black",fill="gray")+
  ggtitle("NBA Teams ranked by Total Salary")+
  xlab("Team")+ylab("Salary(in millions)")+
  coord_flip()+
  geom_hline(yintercept=mean(teams$salary),color="red") ##cuz vertical, vline; if horizontal, then "hline"
```

```{r}
##2nd ranking: bar chart of teams ranked by total points. the vertical line is the average team points
teams<-arrange(teams,points)
ggplot(teams,aes(x=reorder(team, points),y=points))+
  geom_bar(stat='identity',color="black",fill="gray")+
  ggtitle("NBA Teams ranked by Total Points")+
  xlab("Team")+ylab("Total Points")+
  coord_flip() +
  geom_hline(yintercept=mean(teams$points),color="red")
```

```{r}
##3rd ranking, ranked by total efficiency
teams<-arrange(teams,efficiency)
ggplot(teams,aes(x=reorder(team, efficiency) ,y=efficiency))+
  geom_bar(stat='identity',color="black",fill="gray")+
  ggtitle("NBA Teams ranked by Total Efficiency")+
  xlab("Team")+ylab("Total Efficiency")+
  coord_flip() +
  geom_hline(yintercept=mean(teams$efficiency),color="red")
```

```{r}
##comment of rankings
##ranking#1:From the "NBA Teams ranked by Total Salary" ranking, we can see that CLE is the team that has the highest salary, and PHI team has the lowest salary. From the red line that indicates the average salary, we know that the average sarlasy is around 90 missions.

##ranking#2:From the "NBA Teams ranked by Total Points" ranking, we can see that GSW is ranked at top 1 and SAC has the least total points. The average total point for team is around 8000.

##ranking#3: From the "NBA Teams ranked by Total Efficiency" ranking, we can see that CLE is the most efficient team, and ORL has the least efficiency. And the average efficiency among thes NBA teams is around 150
```

```{r}
##PCA:principal components Analysis
#to get a data frame with the eigenvalues
pca1<-select(teams,points3,points2,free_throws,off_rebounds,def_rebounds,assists,steals,blocks,turnovers,fouls)
pca<-prcomp(pca1,scale. = TRUE)##is "true" indicates pca is performed on standardized data(mean=0,var=1)
pca
names
```

```{r}
##creat a data frame with eigenvalues

eigs<-data.frame(team=teams$team,
                   eigenvalue=pca$sdev^2,
                 proportion=round(pca$sdev^2/sum(pca$sdev^2)
                                  ,3),
                 cumprop=cumsum(round(pca$sdev^2/sum(pca$sdev^2)
                                  ,3)),
                 PC1=round(pca$rotation[,1],3),##weight of PC1
                 PC2=round(pca$rotation[,2],3)) ##weight of PC2
eigs                
```

```{r}
##Use PC1 PC2 to get a data frame before getting a scatterplot of the teams
pc_teams<-data.frame(team=teams$team,PC1=round(pca$rotation[,1],3),
                 PC2=round(pca$rotation[,2],3))
pc_teams

ggplot(data=pc_teams, aes(x=PC1,y=PC2),label=team)+
  geom_label(aes(label= team), alpha=0.5,hjust=1,vjust=1)
```

```{r}
##scores
round(head(pca$x,13),1)
round(head(pca$x,13),2)
round(pca$rotation,2)
```

```{r}
##Use PC1 PC2 to get a scatterplot of the teams
PCA<-princomp(pca1,col=T)
PCA
PCA$loadings
loadings<-as.data.frame(PCA$loading[,1:2])
PCA2<-prcomp(pca1)
loadings<-as.data.frame(PCA2$rotation[,1:2])
PCA3<-prcomp(pca1)
loadings<-as.data.frame(PCA3$CA$v.eig[,1:2])

ggplot(data=pc_teams, aes(x=PC1,y=PC2),label=team)+
  geom_label(aes(label= team), alpha=0.5,hjust=1,vjust=1)
```

```{r}
##ranking5: ranked by scaled PC1
teams2<-arrange(pc_teams,PC1)
ggplot(pc_teams,aes(x=reorder(team, PC1) ,y=PC1))+
  geom_bar(stat='identity',color="black",fill="gray")+
  ggtitle("NBA Teams ranked by scaled PC1")+
  xlab("Team")+ylab("First PC(scaled from 0to 100)")+
  coord_flip() 
```

```{r}
##scale:a brief description of PC1 index to rank the teams:the predicted coordinates of the new individuals can be manually calculated as follow:
##1) center and scale the new individual data using the center and the scale of the PCA
##2)calculate the predicted coordinates by mutiplying the scaled values with the eigenvectors(loadings) of the principal components

eig.val=eigs$eigenvalue
eig.val

s1_func<-function(z1,s1){
  s1=100*((z1-min(z1))/(max(z1)-min(z1)))
  apply(s,2,sum)
  }
  
##coordinates of the individividuals
s1_func<- function(z1,s1){
  s<-100*((z1-min(z1))/((max(z1)-min(z1))))
  apply(s,2,sum)
}
```

```{r}
##comments and reflections
## yes. It was a fair peoject,not too hard, not too easy.But it took me longer than I think it should be
## It's my second time to use the related path. My GSI showed me once when i was working on the lab assigbment. I found it very useful. It's easy to place/pull out the files you need/store.
##second time to use R script. Still not really understanding the difference between markdown and script. Like, we need to use %>% in script but not in markdown. I am not sure what else code will change between this two.
##what things were hard? --I thik the PC part was the most hard one for me. I did this project before the lab session. And I have to google a lot to get it done.
##GOOGLE and YOUTUBE are my bestfriends !!
##what's easy? The barchat was okay.
##more time consuming part? --definitly the PC part. And the cvs part as well. I am not quite understand how to deal with the cvs
##How long it took me to finish this hw? --5hours
##interesting?--if fixing the bugs counts, then yes.  
```

